title: Information Securoty - Jaime García
description: "HH IS"
author:
  name: "Jaime García"
  email: #"j.garcia.47@villalkor.com"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Mineja"
year : "2023"

# Html code

#Favicon
favicon: /assets/favicon.png
markdown: kramdown
kramdown:
  math_engine: mathjax